dist: trusty
language: python
python:
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
install:
- python3 -m pip install tqdm
- python3 -m pip install pydiatra pyflakes
- python3 -m pip install restructuredtext-lint pygments
script:
- ./hardball --help
- ./hardball --dry-run .
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
